server:
  port: 29900
  forward-headers-strategy: native
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置
    # driver-class-name: org.h2.Driver
    # url: jdbc:h2:file:~/.halo/db/halo
    # username: admin
    # password: 123456

    # mariadb 配置
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/halodb_huang?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Lr715356!

# MySQL 配置
#     driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#             username: root
#                 password: Lr715356!
  # h2:
    # console:
      # settings:
        # web-allow-others: false
      # path: /h2-console
      # enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
management:
  enabled-by-default: false
  endpoints:
    web:
      # base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health','shutdown']
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  server:
    address: 127.0.0.1
    port: 29901
logging:
  level:
    run.halo.app: INFO
  file:
    path: logs
halo:
  download-timeout: 5m
